/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Contact: typeof import('./src/components/Contact.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    Numbers: typeof import('./src/components/Numbers.vue')['default']
    Overview: typeof import('./src/components/Overview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Whyme: typeof import('./src/components/Whyme.vue')['default']
  }
}
