/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/Banner.vue')['default']
    BannerComponent: typeof import('./src/components/BannerComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    HomeComponent: typeof import('./src/components/HomeComponent.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Numbers: typeof import('./src/components/Numbers.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
